<?php

namespace Game\GameBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BossRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BossRepository extends EntityRepository
{
}
