<?php

namespace Game\GameBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Game\GameBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{

    /**
     * @return array
     */
    public function getInProgressWithBoss()
    {
        $qb = $this->createQueryBuilder('game');

        $qb
            ->select('game, boss')
            ->join('game.boss', 'boss')
            ->where('game.status = :status')
            ->setParameters(array('status' => Game::STATUS_IN_PROGRESS));

        return $qb->getQuery()->getResult();
    }
}
