<?php

namespace Game\QuestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestRepository extends EntityRepository
{
}
