<?php

namespace Game\QuestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestInstanceRepository extends EntityRepository
{
    /**
     * @param $char
     * @param $quest
     * @param $status
     * @return mixed
     */
    public function getQuestInstanceForStatus($char, $quest, $status)
    {
        $qb = $this->createQueryBuilder('qi');

        $qb
            ->join('qi.companion', 'comp')
            ->where('comp.character = :char')
            ->andWhere('qi.quest = :quest')
            ->andWhere('qi.status = :status')
            ->setParameters(array('char' => $char, 'quest' => $quest, 'status'=>$status));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
