<?php

namespace Game\QuestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Game\QuestBundle\Entity\QuestInstance;

/**
 * QuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestRepository extends EntityRepository
{
    /**
     * @param $lvl
     * @return array
     */
    public function findQuests($lvl)
    {
        $qb = $this->createQueryBuilder('quest');

        $qb
            ->select('quest')
            //->join('quest.questInstances', 'qin')
            //->join('qin.companion', 'comp')
            ->where('quest.level <= :lvl')
            ->setParameters(array('lvl' => $lvl,));

        return $qb->getQuery()->getArrayResult();
    }
}
