<?php

namespace Game\ItemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArmorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorRepository extends EntityRepository
{

}
