<?php

namespace Game\ItemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends EntityRepository
{
    /**
     * Devuelve las armas equipadas de un personaje
     *
     * @param $char
     * @return array
     */
    public function getEquippedWeapons($char)
    {
        $qb = $this->createQueryBuilder('weapon');
        $qb
            ->select('weapon')
            ->innerJoin('weapon.characterItems', 'charItem')
            ->innerJoin('charItem.character', 'char')
            ->where('char = :char')
            ->andWhere('charItem.equipped = :equipped')
            ->setParameter(':char', $char)
            ->setParameter(':equipped', true);

        return $qb->getQuery()->getResult();
    }
}
