<?php

namespace Game\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterItemRepository extends EntityRepository
{
}
