<?php

namespace Game\MonsterBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LootItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LootItemRepository extends EntityRepository
{
}
