<?php

namespace Game\CompanionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanionRepository extends EntityRepository
{
}
