<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Game\MapBundle\Entity\Poi;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
    /**
     * Busca un Path que vaya en dirección al Poi
     *
     * @param Poi $start
     * @param Poi $end
     * @internal param \Game\MapBundle\Entity\Poi $poi
     * @return mixed
     */
    public function findPathToPoi(Poi $start, Poi $end)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM GameMapBundle:Path p WHERE p.start=:start AND p.end=:end')
            ->setParameter('start', $start)
            ->setParameter('end', $end);

        return $query->getOneOrNullResult();
    }
}
