<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Game\MapBundle\Entity\Poi;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{

}
