<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathRepository extends EntityRepository
{
}
