<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoiRepository extends EntityRepository
{
    /**
     * gamedo: Doctrine no tiene para RANDOM, optimizar esta query
     * @return mixed
     */
    public function getRandomNotInfected()
    {
        $qb = $this->createQueryBuilder('poi');

        $qb
            ->where('poi.infected = :infected')
            ->setParameters(array('infected' => false));

        $results = $qb->getQuery()->getResult();
        shuffle($results);
        return $results[0];
    }
}
