<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoiRepository extends EntityRepository
{
    /**
     * gamedo: Doctrine no tiene para RANDOM, optimizar esta query
     * @param $game
     * @return mixed
     */
    public function getRandomNotInfected($game)
    {
        $qb = $this->createQueryBuilder('poi');

        $qb
            ->join('poi.map', 'map')
            ->join('map.game', 'game')
            ->where('poi.infected = :infected')
            ->andWhere('game = :game')
            ->setParameters(array('infected' => false, 'game' => $game));

        $results = $qb->getQuery()->getResult();
        if ($results) {
            shuffle($results);
            return $results[0];
        } else {
            return null;
        }
    }

    public function findStartingPoi($game)
    {
        $qb = $this->createQueryBuilder('poi');

        $qb
            ->join('poi.map', 'map')
            ->join('map.game', 'game')
            ->where('game = :game')
            ->andWhere('poi.startPoint = 1')
            ->setParameters(array('game' => $game));

        $results = $qb->getQuery()->getResult();
        if ($results) {
            shuffle($results);
            return $results[0];
        } else {
            return null;
        }
    }
}
