<?php

namespace Game\MapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TreasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreasureRepository extends EntityRepository
{
}
