<?php

namespace Game\BattleBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends EntityRepository
{
}
