<?php

namespace Game\ItemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends EntityRepository
{
}
