<?php

namespace Game\CharacterBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterClassRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findClasses()
    {
        $qb = $this->createQueryBuilder('characterclass');
        $qb->select('characterclass');

        return $qb->getQuery()->getArrayResult();
    }
}
